package:
  name: ezdxf
  version: "0.8.2"

source:
  fn: ezdxf-0.8.2.tar.gz
  url: https://github.com/mozman/ezdxf/archive/v0.8.2.tar.gz
  sha256: 60ebedbb0c6ec3071af81f01247a3e09afef0c325b7448fb409331755a844008

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.0.1

  run:
    - python
    - pyparsing >=2.0.1

test:
  # Python imports
  imports:
    - ezdxf
    - ezdxf.legacy
    - ezdxf.lldxf
    - ezdxf.modern
    - ezdxf.pp
    - ezdxf.sections
    - ezdxf.templates
    - ezdxf.tools


about:
  home: http://github.com/mozman/ezdxf.git
  license: MIT License
  summary: 'A Python package to create/manipulate DXF drawings.'
  license_family: MIT
