package:
    name: meshpy
    version: "2016.1.2"

source:
    git_url: https://github.com/inducer/meshpy
    git_tag: master

build:
    number: 4

requirements:
    build:
        - cmake
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - python
        - setuptools
        - boost >=1.66*
        - pytools >=2011.2
        - pytest >=2
        - numpy

    run:
        - vc 14  # [win and py>=35]
        - python
        - boost >=1.66*
        - pytools >=2011.2
        - pytest >=2
        - numpy

test:
    requirements:
        - boost >=1.66*
    imports:
        - meshpy
        - meshpy.triangle

about:
    home: http://mathema.tician.de/software/meshpy
    license: MIT License
    summary: 'Triangular and Tetrahedral Mesh Generator'

