package:
  name: meshpy
  version: "2016.1.2"

source:
  fn: MeshPy-2016.1.2.tar.gz
  url: https://github.com/inducer/meshpy/archive/v2016.1.2.tar.gz
  md5: 543462bc4f5ae74041ba0a1675503847
  patches: 
    -config.patch
build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - meshpy = meshpy:main
    #
    # Would create an entry point called meshpy that calls meshpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - gcc
    - python
    - setuptools
    - boost 1.63.0
    - pytools >=2011.2  # https://conda.anaconda.org/omnia
    - pytest >=2
    - numpy

  run:
    - gcc # [unix]
    - python
    - pytools >=2011.2  # https://conda.anaconda.org/omnia
    - pytest >=2
    - numpy

test:
  # Python imports
  requirements:
    - gcc # [unix]
  imports:
    - meshpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mathema.tician.de/software/meshpy
  license: MIT License
  summary: 'Triangular and Tetrahedral Mesh Generator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
