{%set name = "meshpy"%}
{%set version = "2018.2.1"%}
{%set sha256 = "167e1f4d74d1fd139e303fae1e57c5a7c1b98c9f1f31f92a017597c1554e0a3d"%}


package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    url: https://github.com/inducer/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0

requirements:
    build:
        - {{ compiler('cxx') }}
        - ninja  # [win]
    host:
        - python
        - setuptools
        - pybind11
        - pytools
        - pytest
        - numpy

    run:
        - python
        - pytools
        - numpy

test:
    imports:
        - meshpy
        - meshpy.triangle

about:
    home: http://mathema.tician.de/software/meshpy
    license: MIT License
    summary: 'Triangular and Tetrahedral Mesh Generator'

extra:
    recipe-maintainers:
        - looooo