{%set name = "meshpy"%}
{%set version = "2018.1"%}
{%set sha256 = "dbfda01cb23020cbbfcc0c83d5872c95e4fe532679b56b7ba65f445bdcc85c8c"%}


package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    url: https://github.com/inducer/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
        - boost.patch

build:
    number: 0
    skip: true  # [win and py<35]

requirements:
    build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja  # [win]
    host:
        - python
        - setuptools
        - boost
        - pytools
        - pytest
        - numpy

    run:
        - python
        - boost
        - pytools
        - pytest
        - numpy

test:
    requirements:
        - boost
    imports:
        - meshpy
        - meshpy.triangle

about:
    home: http://mathema.tician.de/software/meshpy
    license: MIT License
    summary: 'Triangular and Tetrahedral Mesh Generator'

extra:
    recipe-maintainers:
        - looooo