package:
  name: meshpy
  version: "2016.1.2"

source:
  fn: MeshPy-2016.1.2.tar.gz
  url: https://github.com/inducer/meshpy/archive/v2016.1.2.tar.gz
  md5: 543462bc4f5ae74041ba0a1675503847
  patches: 
    - config.patch
    - boost_1.64.patch
    - win1.patch  # [win]
build:
  number: 1

requirements:
  build:
    - vc 14  # [win and py>=35]
    - ninja  # [win and py>=35]
    - gcc  # [unix]
    - python
    - setuptools
    - boost >=1.64*
    - pytools >=2011.2
    - pytest >=2
    - numpy

  run:
    - vc 14  # [win and py>=35]
    - python
    - boost >=1.64*
    - pytools >=2011.2
    - pytest >=2
    - numpy

test:
  # Python imports
  requirements:
    - gcc # [unix]
  imports:
    - meshpy

about:
  home: http://mathema.tician.de/software/meshpy
  license: MIT License
  summary: 'Triangular and Tetrahedral Mesh Generator'

