package:
  name: meshpy
  version: "2016.1.2"

source:
  fn: meshpy.tar.gz
  url: https://github.com/looooo/meshpy/archive/master.tar.gz

build:
  number: 1

requirements:
  build:
    - cmake
    - vc 14  # [win and py>=35]
    - ninja  # [win and py>=35]
    - gcc  # [unix]
    - python
    - setuptools
    - boost >=1.64*
    - pytools >=2011.2
    - pytest >=2
    - numpy

  run:
    - vc 14  # [win and py>=35]
    - python
    - boost >=1.64*
    - pytools >=2011.2
    - pytest >=2
    - numpy

test:
  # Python imports
  requirements:
    - gcc # [unix]
    - boost >=1.64*
  imports:
    - meshpy
    - meshpy.triangle

about:
  home: http://mathema.tician.de/software/meshpy
  license: MIT License
  summary: 'Triangular and Tetrahedral Mesh Generator'

