package:
  name: svgwrite
  version: !!str 1.1.11

source:
  fn: svgwrite-1.1.11.tar.gz
  url: https://github.com/mozman/svgwrite/archive/1.1.11.tar.gz
  sha256: eb559c33ed88619a0d9c6efe2ad9da889f360b16252dfd4e7537c796eaf07ab7

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.0.1

  run:
    - python
    - pyparsing >=2.0.1

test:
  # Python imports
  imports:
    - svgwrite

about:
  home: http://bitbucket.org/mozman/svgwrite
  license: MIT License
  summary: 'A Python library to create SVG drawings.'
