{% set name = "py-xflr5" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 1

source:
  git_url: https://github.com/looooo/xfoil-python

requirements:
  build:
    - {{ compiler("cxx") }}
    - ninja
    - cmake
  host:
    - python
    - pybind11
    - eigen
    - qt
  run:
    - python
    - numpy
    - qt

test:
  imports:
    - xfoil

about:
  summary: python bindings to xfoil

extra:
  recipe-maintainers:
    - looooo