package:
  name: laplacekernels
  version: 0.0.1

build:
  number: 4

source:
  path: https://github.com/looooo/laplace_kernels.git

requirements:
  build:
    - python
    - pybind11        # pybind
    - cmake
    - eigen           # rmg
    - paraeigen       # openglider
  run:
    - python
    - paraeigen

about:
summary: Some laplace kernels