package:
  name: parabem
  version: 0.0.1

build:
  number: 4

source:
  git_url: https://github.com/booya-at/paraBEM

requirements:
  build:
    - python
    - cmake
    - pybind11
    - eigen
  run:
    - python
    - paraeigen         #   - looooo
    - numpy
    - matplotlib

about:
  summary: potential flow with boundary elements.