package:
    name: parabem
    version: 0.1.0

build:
    number: 0

source:
    git_url: https://github.com/booya-at/paraBEM

requirements:
    build:
        - {{ compiler('cxx') }}
        - ninja
        - cmake
    host:
        - python
        - pybind11
        - eigen
        - openmpi  # [unix]
    run:
        - python
        - numpy
        - matplotlib
test:
    imports:
        - paraBEM

about:
    summary: potential flow with boundary elements.
