package:
  name: parabem
  version: 0.1.0

build:
  number: 0

source:
  git_url: https://github.com/booya-at/paraBEM

requirements:
  build:
    - vc 14  # [win and py>=35]
    - ninja
    - python
    - cmake
    - pybind11 2.2.*
    - eigen
    - openmpi  # [unix]
  run:
    - vc 14  # [win and py>=35]
    - python
    - numpy
    - matplotlib
test:
  imports:
    - paraBEM

about:
  summary: potential flow with boundary elements.
