package:
  name: parabem
  version: 0.0.1

build:
  number: 4

source:
  git_url: https://github.com/booya-at/paraBEM

requirements:
  build:
    - ninja  # [win]
    - vc 14  # [win and py>=35]
    - python
    - cmake
    - pybind11
    - eigen
  run:
    - vc 14  # [win and py>=35]
    - python
    - paraeigen
    - numpy
    - matplotlib

about:
  summary: potential flow with boundary elements.