package:
  name: parafem
  version: 0.0.1

build:
  number: 3

source:
  git_url: https://github.com/booya-at/paraFEM

requirements:
  build:
    - python
    - cmake
    - pybind11          #   - pybind
    - eigen             #   - looooo
    - vtk
  run:
    - python
    - paraeigen         #   - looooo
    - numpy
    - matplotlib

about:
  summary: explicit fem for membrane elements
