package:
  name: parafem
  version: 0.0.1

build:
  number: 4

source:
  git_url: https://github.com/booya-at/paraFEM

requirements:
  build:
    - ninja
    - python
    - cmake
    - pybind11
    - eigen
    - vtk
  run:
    - python
    - numpy
    - matplotlib
    - vtk

test:
  imports:
    - paraFEM

about:
  summary: explicit fem for membrane elements
