package:
    name: paraeigen
    version: 0.0.1

build:
    number: 4

source:
    git_url: https://github.com/looooo/paraEigen
    git_tag: master

requirements:
    build:
        - {{ compiler('cxx') }}
        - ninja
        - cmake
    host:
        - python
        - pybind11
        - eigen
        - openmpi  # [unix]
    run:
        - python

test:
    imports:
        - paraEigen

about:
    summary: some eigen-wrappers
