package:
  name: paraeigen
  version: 0.0.1

build:
  number: 4

source:
  git_url: https://github.com/looooo/paraEigen

requirements:
  build:
    - python
    - pybind11          #   - conda-forge
    - eigen 3.3         #   - looooo
  run:
    - python

about:
  summary: some eigen-wrappers
