package:
  name: paraeigen
  version: 0.0.1

build:
  number: 4

source:
  git_url: https://github.com/looooo/paraEigen
  git_tag: master

requirements:
  build:
    - cmake
    - python
    - pybind11
    - eigen 3.3*
  run:
    - python

about:
  summary: some eigen-wrappers
