package:
  name: freecad-glider
  version: 0.0.1

source:
  git_url: https://github.com/booya-at/freecad_glider
  git_tag: singleskin

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - openglider
    - freecad

about:
  summary: paraglider design