package:
  name: freecad-glider
  version: 0.0.1

build:
  number: 0

source:
  git_url: https://github.com/booya-at/freecad_glider
  git_tag: master

requirements:
  run:
    - python
    - openglider
    - freecad

about:
  summary: paraglider design