{%set name = "freecad-glider"%}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/booya-at/{{ freecad-glider }}
  git_tag: master

build:
  number: 3
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - openglider
    - freecad

about:
  summary: paraglider design
