package:
  name: ezodf
  version: "0.3.2"

source:
  fn: ezodf-0.3.2.tar.gz
  url: https://pypi.python.org/packages/6f/c5/e966935c26d58d7e3d962270be61be972409084374d4093f478d1f82e8af/ezodf-0.3.2.tar.gz
  md5: b12670b60b49d3c35338fd46493071fc
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ezodf = ezodf:main
    #
    # Would create an entry point called ezodf that calls ezodf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - lxml

  run:
    - python
    - lxml

test:
  # Python imports
  imports:
    - ezodf

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/T0ha/ezodf
  license: MIT License
  summary: 'A Python package to create/manipulate OpenDocumentFormat files.'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
