{%set name = "openglider"%}
{%set version = "0.0.1"%}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/booya-at/OpenGlider.git
  git_tag: develop

build:
  number: 11
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip
  run:
    - python
    - meshpy
    - parabem
    - numpy
    - ezodf
    - svgwrite
    - ezdxf
    - lxml

test:
  imports:
    - openglider

about:
  summary: paraglider design
