{% set name = "openglider" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/booya-at/OpenGlider.git
  git_tag: develop

build:
  number: 19
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - pip
    - python
  run:
    - python
    - numpy
    - ezodf
    - svgwrite
    - ezdxf
    - lxml
    - parabem
    - meshpy
    - pyexcel-ezodf

test:
  imports:
    - openglider

about:
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: paraglider design

extra:
  recipe-maintainers:
    - looooo