package:
  name: openglider
  version: 0.0.1

build:
  number: 8

source:
  git_url: https://github.com/booya-at/OpenGlider.git
  git_tag: develop

requirements:
  build:
    - python
    - meshpy
    - parabem
    - numpy
    - ezodf
    - lxml
    - ezdxf
    - svgwrite
  run:
    - python
    - meshpy
    - parabem
    - matplotlib
    - numpy
    - ezodf
    - svgwrite
    - ezdxf
    - lxml

test:
  imports:
    - openglider

about:
  summary: paraglider design
